restricted individual user actions to 'offer' only
uaem-na/donations-tracker pull request #95
Opened 2023-10-24 22:12 UTC by jateen67

restricted individual actions to only being able to create 'offer' posts and not 'requests' posts. also removed the 'requests' filter from the individual user's 'my posts' page.

2023-10-25 22:36 UTC, shjryan requested changes
Thanks for this PR!

Going over the changes, I wonder if it would be a good idea for us to start using react context and a hook to track current page. What do you think?

2023-10-25 22:36 UTC, shjryan commented on frontend/src/components/Posts/FilterContainer.tsx
> +  header,
What's the purpose of `header` prop?

Is it because we need to know which page we are on?

2023-10-25 22:36 UTC, shjryan commented on frontend/src/components/Posts/FilterContainer.tsx
> +  const hideFiltersFromIndividual = (postType: string) => {
I think this should be renamed to match the boolean return type.

if `hideFiltersFromIndividual()` returns true, then this component will render.
if `hideFiltersFromIndividual()` returns false, then this component will not render the filter option.

To me, that kind of contradicts the promise between variable name and output.

What if we renamed it to something like `showFilterForIndividual()`?

2023-10-26 00:18 UTC, jateen67 commented
Hi Ryan!

The `header` prop is needed to know what tab the user is on in their dashboard. I believe the requests filter should be removed from the user's `My posts` tab only, and the `Favorites` tab's filters should not be altered. I need to pass in the header so that I know what tab I'm on, and if I'm on `My posts`, then I don't render the requests filter.

As for React Context, as you said, for this issue it wouldn't be needed, but it could be helpful in the future. The `header` prop (among others) is being passed down many different components, so if it's something you're considering, we could maybe implement it to make things a bit cleaner.

Thanks for the feedback!

@shjryan

2023-10-26 00:54 UTC, shjryan approved these changes

2023-10-26 00:55 UTC, merged