#78: disable and set price input fields to 0 for donation offers and request
uaem-na/donations-tracker pull request #96
Opened 2023-10-24 23:55 UTC by olaabi

Added a checkbox for disabling price fields when the offer/request is a donation to both create and edit post forms

2023-10-25 23:10 UTC, shjryan requested changes
Thanks for the PR! Please review the comments below.

2023-10-25 23:10 UTC, shjryan commented on frontend/public/locales/en/common.json
> +    "is_donation": "Donation?",
Could you add the French equivalent in `/public/locales/fr/common.json`? The value can be the same as English. Adding bilingual support will be another future issue.

Also, I think it's better to use key `donation` and get rid of the question mark in the value so that we can reuse the word everywhere else. We can append the question mark in code.

2023-10-25 23:10 UTC, shjryan commented on frontend/src/pages/Posts/components/CreatePostForm.tsx
> +                  onChange: (e) => setIsDonation(!isDonation),
1. Could we create a handler function for this?
2. Could we use a functional form of `setState` to set the state to prevent unexpected behaviour as this fn is async? e.g. `setIsDonation(prev => !prev)`
3. Could we set the value of `item.price` by using `setValue` from `useForm` hook, in the handler? 

[React Hook Form - setValue](https://www.react-hook-form.com/api/useform/setvalue/)

2023-10-25 23:10 UTC, shjryan commented on frontend/src/pages/Posts/components/EditPostForm.tsx
I think we can set the default value of `isDonation` state after line 97 by checking `post.item.price` if post loads successfully.

2023-10-26 09:02 UTC, olaabi commented
Hey Ryan, thanks for the review and apologies for the delay. 😅 
I added the changes you requested above; please let me know if there's anything else you need me to update!

2023-10-27 03:04 UTC, shjryan approved these changes
Awesome! Thanks for the changes.

2023-10-27 03:04 UTC, merged